server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.140.129:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    initialize: false
  jpa:
    database: mysql
    show-sql: true
   cloud:
    refresh:
      refreshable: none
  rabbitmq:
    host: 192.168.140.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
  
