server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.140.129
      database: spitdb
  redis:
    host: 192.168.140.129
  cloud:
    refresh:
      refreshable: none
  rabbitmq:
    host: 192.168.140.129    
